
TOP=../../../../..
include $(TOP)/tests/mk/test.mk

RTL=$(TOP)/rtl
VFILES+=../testbench/bench.v
VFILES+=$(RTL)/lib/ram.v
VFILES+=$(RTL)/lib/ff.v
VFILES+=$(RTL)/hmem/hmem_dualram.v
VFILES+=$(RTL)/hmem/hmem_heap.v

